package store

import "mealapp-backend/internal/models"

func DefaultMealLibraryItems() []models.MealLibraryItem {
	return []models.MealLibraryItem{
		item(models.MealSlotBreakfast, models.CuisineAfrican, "Pap, moi moi, and citrus fruit", "Steamed bean pudding with fermented corn custard and vitamin-rich fruit.", 430, "24g", "25 min", []string{"High fiber", "Heart friendly", "Filling"}, []string{"beans", "corn", "orange"}, []string{"vegetarian", "no restriction"}, nil),
		item(models.MealSlotBreakfast, models.CuisineAfrican, "Millet porridge with banana and seeds", "Warm millet porridge topped with banana, chia, cinnamon, and a boiled egg on the side.", 410, "23g", "18 min", []string{"Energy steady", "High fiber", "Balanced"}, []string{"millet", "banana", "chia", "egg"}, []string{"no restriction"}, []string{"egg"}),
		item(models.MealSlotBreakfast, models.CuisineAfrican, "Akara breakfast salad plate", "Baked black-eyed pea fritters with tomato cucumber salad, avocado, and pepper sauce.", 440, "25g", "24 min", []string{"Plant protein", "Fiber rich", "Balanced"}, []string{"black-eyed beans", "tomato", "cucumber", "avocado", "pepper"}, []string{"vegetarian", "no restriction"}, nil),
		item(models.MealSlotBreakfast, models.CuisineFrench, "Herb omelette with ratatouille toast", "Eggs, tomatoes, zucchini, and peppers served on toasted whole grain bread.", 390, "27g", "18 min", []string{"Low sugar", "Protein rich", "Vegetable packed"}, []string{"egg", "tomato", "zucchini", "pepper", "bread"}, []string{"no restriction", "vegetarian"}, []string{"egg", "gluten"}),
		item(models.MealSlotBreakfast, models.CuisineFrench, "Berry fromage bowl", "High-protein yogurt with berries, oats, flax, and toasted almonds.", 380, "30g", "8 min", []string{"Protein rich", "Gut friendly", "No cook"}, []string{"yogurt", "berries", "oats", "flax", "almonds"}, []string{"vegetarian", "no restriction"}, []string{"dairy", "tree nuts"}),
		item(models.MealSlotBreakfast, models.CuisineFrench, "Smoked trout tartine with greens", "Whole grain tartine with smoked trout, lemon herbs, radish, greens, and apple slices.", 420, "31g", "12 min", []string{"Protein rich", "Fresh", "Heart healthy"}, []string{"trout", "bread", "radish", "greens", "apple"}, []string{"pescatarian", "no restriction"}, []string{"fish", "gluten"}),
		item(models.MealSlotBreakfast, models.CuisineChinese, "Congee with egg and greens", "Brown rice congee with soft egg, ginger, spinach, and sesame scallions.", 360, "21g", "22 min", []string{"Gentle digestion", "Hydrating", "Warm"}, []string{"brown rice", "egg", "ginger", "spinach", "sesame"}, []string{"no restriction", "vegetarian"}, []string{"egg", "sesame"}),
		item(models.MealSlotBreakfast, models.CuisineChinese, "Tofu vegetable breakfast bowl", "Seared tofu, bok choy, mushrooms, brown rice, ginger, and light soy.", 390, "28g", "20 min", []string{"Plant protein", "Low oil", "Balanced"}, []string{"tofu", "bok choy", "mushrooms", "brown rice", "soy"}, []string{"vegetarian", "no restriction"}, []string{"soy"}),
		item(models.MealSlotBreakfast, models.CuisineChinese, "Scallion egg rice roll bowl", "Steamed rice rolls with scallion egg, cucumber, greens, and light ginger sauce.", 400, "24g", "18 min", []string{"Warm", "Balanced", "Low oil"}, []string{"rice", "egg", "scallion", "cucumber", "ginger"}, []string{"no restriction", "vegetarian"}, []string{"egg"}),
		item(models.MealSlotBreakfast, models.CuisineMediterranean, "Greek yogurt mezze bowl", "Greek yogurt, cucumber, chickpeas, olives, herbs, and seeded flatbread.", 410, "29g", "10 min", []string{"Gut friendly", "Lean protein", "No cook"}, []string{"yogurt", "cucumber", "chickpeas", "olives", "flatbread"}, []string{"vegetarian", "no restriction"}, []string{"dairy", "gluten"}),
		item(models.MealSlotBreakfast, models.CuisineMediterranean, "Chickpea avocado breakfast plate", "Chickpeas, avocado, tomato, cucumber, herbs, lemon, and boiled egg.", 430, "24g", "12 min", []string{"Fiber rich", "Balanced", "Fresh"}, []string{"chickpeas", "avocado", "tomato", "cucumber", "egg"}, []string{"no restriction", "vegetarian"}, []string{"egg"}),
		item(models.MealSlotBreakfast, models.CuisineMediterranean, "Shakshuka with white beans", "Eggs poached in tomato pepper sauce with white beans, parsley, and cucumber.", 430, "28g", "22 min", []string{"Protein rich", "Vegetable packed", "Warm"}, []string{"egg", "tomato", "pepper", "white beans", "parsley"}, []string{"vegetarian", "no restriction"}, []string{"egg"}),
		item(models.MealSlotBreakfast, models.CuisineIndian, "Vegetable poha with boiled egg", "Flattened rice cooked with peas, carrots, turmeric, peanuts, and lemon.", 420, "22g", "20 min", []string{"Balanced carbs", "Spiced", "Energy steady"}, []string{"rice", "peas", "carrots", "turmeric", "peanuts", "egg"}, []string{"no restriction", "vegetarian"}, []string{"peanuts", "egg"}),
		item(models.MealSlotBreakfast, models.CuisineIndian, "Moong dal chilla with mint chutney", "Lentil pancakes filled with spinach and tomato, served with cooling mint chutney.", 400, "26g", "24 min", []string{"Plant protein", "Low sugar", "Fiber rich"}, []string{"lentils", "spinach", "tomato", "mint"}, []string{"vegetarian", "no restriction"}, nil),
		item(models.MealSlotBreakfast, models.CuisineIndian, "Masala oats with chickpeas", "Savory oats cooked with chickpeas, tomato, peas, turmeric, cumin, and coriander.", 410, "24g", "18 min", []string{"Fiber rich", "Energy steady", "Plant protein"}, []string{"oats", "chickpeas", "tomato", "peas", "turmeric"}, []string{"vegetarian", "no restriction"}, nil),

		item(models.MealSlotLunch, models.CuisineAfrican, "Jollof quinoa with grilled fish", "Tomato-pepper quinoa, grilled fish, avocado, and crunchy cabbage salad.", 560, "38g", "30 min", []string{"Omega-3", "Whole grain", "Colorful"}, []string{"quinoa", "fish", "avocado", "cabbage"}, []string{"pescatarian", "no restriction"}, []string{"fish"}),
		item(models.MealSlotLunch, models.CuisineAfrican, "Black-eyed bean and vegetable bowl", "Stewed black-eyed beans with greens, tomato, peppers, brown rice, and avocado.", 520, "29g", "28 min", []string{"Plant protein", "Fiber rich", "Balanced"}, []string{"beans", "greens", "tomato", "pepper", "brown rice", "avocado"}, []string{"vegetarian", "no restriction"}, nil),
		item(models.MealSlotLunch, models.CuisineAfrican, "Suya chicken power bowl", "Grilled suya-spiced chicken with fonio, cucumber, tomato, cabbage, and yogurt herb sauce.", 560, "45g", "28 min", []string{"High protein", "Balanced", "Colorful"}, []string{"chicken", "fonio", "cucumber", "tomato", "cabbage", "yogurt"}, []string{"no restriction"}, []string{"dairy"}),
		item(models.MealSlotLunch, models.CuisineFrench, "Nicoise-inspired salmon salad", "Salmon, greens, eggs, green beans, potatoes, olives, and mustard vinaigrette.", 540, "41g", "24 min", []string{"Heart healthy", "Balanced", "Fresh"}, []string{"salmon", "egg", "green beans", "potatoes", "olives"}, []string{"pescatarian", "no restriction"}, []string{"fish", "egg"}),
		item(models.MealSlotLunch, models.CuisineFrench, "Lentil salade composee", "French lentils, roasted carrots, herbs, greens, apple, walnuts, and mustard dressing.", 500, "27g", "22 min", []string{"Fiber rich", "Heart healthy", "Fresh"}, []string{"lentils", "carrots", "greens", "apple", "walnuts"}, []string{"vegetarian", "no restriction"}, []string{"tree nuts"}),
		item(models.MealSlotLunch, models.CuisineFrench, "Turkey lettuce bistro bowl", "Lean turkey, roasted potatoes, green beans, lettuce, herbs, and light Dijon dressing.", 530, "42g", "26 min", []string{"Lean protein", "Fresh", "Balanced"}, []string{"turkey", "potatoes", "green beans", "lettuce", "dijon"}, []string{"no restriction"}, nil),
		item(models.MealSlotLunch, models.CuisineChinese, "Ginger chicken brown rice bowl", "Lean chicken, broccoli, mushrooms, carrots, brown rice, and light soy ginger sauce.", 520, "43g", "28 min", []string{"Lean protein", "Low oil", "Meal prep"}, []string{"chicken", "broccoli", "mushrooms", "carrots", "brown rice", "soy"}, []string{"no restriction"}, []string{"soy"}),
		item(models.MealSlotLunch, models.CuisineChinese, "Mapo tofu vegetable bowl", "Tofu, edamame, mushrooms, bok choy, brown rice, and a light chili bean sauce.", 510, "32g", "25 min", []string{"Plant protein", "Balanced", "Low oil"}, []string{"tofu", "edamame", "mushrooms", "bok choy", "brown rice", "soy"}, []string{"vegetarian", "no restriction"}, []string{"soy"}),
		item(models.MealSlotLunch, models.CuisineChinese, "Five-spice turkey lettuce cups", "Five-spice turkey with carrots, water chestnuts, brown rice, lettuce, and cucumber.", 500, "40g", "24 min", []string{"Lean protein", "Low oil", "Fresh"}, []string{"turkey", "carrots", "water chestnuts", "brown rice", "lettuce"}, []string{"no restriction"}, nil),
		item(models.MealSlotLunch, models.CuisineMediterranean, "Chicken shawarma grain bowl", "Spiced chicken, bulgur, hummus, cucumber, tomato, parsley, and tahini yogurt.", 570, "44g", "26 min", []string{"High protein", "Fiber rich", "Bright"}, []string{"chicken", "bulgur", "hummus", "cucumber", "tomato", "tahini", "yogurt"}, []string{"no restriction"}, []string{"gluten", "sesame", "dairy"}),
		item(models.MealSlotLunch, models.CuisineMediterranean, "Falafel quinoa salad", "Baked falafel, quinoa, tomato, cucumber, parsley, hummus, and lemon tahini.", 540, "28g", "25 min", []string{"Plant protein", "Fiber rich", "Balanced"}, []string{"falafel", "quinoa", "tomato", "cucumber", "hummus", "tahini"}, []string{"vegetarian", "no restriction"}, []string{"sesame"}),
		item(models.MealSlotLunch, models.CuisineMediterranean, "Tuna tabbouleh protein plate", "Tuna, parsley tabbouleh, cucumber, tomato, chickpeas, olives, and lemon dressing.", 520, "39g", "18 min", []string{"High protein", "Fresh", "Heart healthy"}, []string{"tuna", "parsley", "cucumber", "tomato", "chickpeas", "olives"}, []string{"pescatarian", "no restriction"}, []string{"fish"}),
		item(models.MealSlotLunch, models.CuisineIndian, "Lentil dal with brown basmati", "Yellow lentils, spinach, turmeric, cumin, brown rice, and cucumber raita.", 530, "30g", "32 min", []string{"Plant protein", "Iron source", "Comforting"}, []string{"lentils", "spinach", "brown rice", "cucumber", "yogurt"}, []string{"vegetarian", "no restriction"}, []string{"dairy"}),
		item(models.MealSlotLunch, models.CuisineIndian, "Tandoori paneer salad", "Paneer, chickpeas, greens, cucumber, tomato, mint, and lemon dressing.", 550, "35g", "24 min", []string{"Protein rich", "Fresh", "Balanced"}, []string{"paneer", "chickpeas", "greens", "cucumber", "tomato"}, []string{"vegetarian", "no restriction"}, []string{"dairy"}),
		item(models.MealSlotLunch, models.CuisineIndian, "Chicken tikka millet bowl", "Tandoori-spiced chicken with millet, cucumber, tomato, greens, and mint chutney.", 560, "44g", "26 min", []string{"High protein", "Balanced", "Spiced"}, []string{"chicken", "millet", "cucumber", "tomato", "greens", "mint"}, []string{"no restriction"}, nil),

		item(models.MealSlotDinner, models.CuisineAfrican, "Efo riro with baked plantain", "Spinach stew with turkey, peppers, beans, and oven-baked plantain slices.", 590, "42g", "35 min", []string{"Iron rich", "Satisfying", "Low fry"}, []string{"spinach", "turkey", "peppers", "beans", "plantain"}, []string{"no restriction"}, nil),
		item(models.MealSlotDinner, models.CuisineAfrican, "Vegetable egusi-style stew", "Pumpkin seed vegetable stew with mushrooms, spinach, tomato, and cauliflower swallow.", 530, "31g", "34 min", []string{"Plant protein", "Low carb", "Iron rich"}, []string{"pumpkin seed", "mushrooms", "spinach", "tomato", "cauliflower"}, []string{"vegetarian", "no restriction", "low carb"}, []string{"seeds"}),
		item(models.MealSlotDinner, models.CuisineAfrican, "Grilled chicken pepper soup bowl", "Pepper soup-spiced chicken with vegetables, sweet potato cubes, herbs, and greens.", 540, "43g", "32 min", []string{"High protein", "Warm", "Balanced"}, []string{"chicken", "sweet potato", "greens", "pepper", "herbs"}, []string{"no restriction"}, nil),
		item(models.MealSlotDinner, models.CuisineFrench, "Chicken provencal with barley", "Tomato herb chicken with olives, roasted vegetables, and nutty barley.", 570, "45g", "34 min", []string{"Lean", "Herb forward", "Slow carbs"}, []string{"chicken", "tomato", "olives", "vegetables", "barley"}, []string{"no restriction"}, []string{"gluten"}),
		item(models.MealSlotDinner, models.CuisineFrench, "Ratatouille with white beans", "Slow-cooked eggplant, zucchini, tomato, peppers, herbs, and white beans.", 480, "26g", "32 min", []string{"Vegetable packed", "Fiber rich", "Low sugar"}, []string{"eggplant", "zucchini", "tomato", "peppers", "beans"}, []string{"vegetarian", "no restriction", "low carb"}, nil),
		item(models.MealSlotDinner, models.CuisineFrench, "Seared cod with warm lentils", "Cod with French lentils, carrots, leeks, herbs, lemon, and steamed greens.", 520, "42g", "30 min", []string{"Lean protein", "Heart healthy", "Balanced"}, []string{"cod", "lentils", "carrots", "leeks", "greens"}, []string{"pescatarian", "no restriction"}, []string{"fish"}),
		item(models.MealSlotDinner, models.CuisineChinese, "Steamed fish with bok choy", "Ginger scallion fish, bok choy, edamame, and a small serving of jasmine rice.", 510, "46g", "26 min", []string{"Light dinner", "High protein", "Low saturated fat"}, []string{"fish", "bok choy", "edamame", "rice", "soy"}, []string{"pescatarian", "no restriction"}, []string{"fish", "soy"}),
		item(models.MealSlotDinner, models.CuisineChinese, "Garlic tofu and broccoli stir-fry", "Tofu, broccoli, snap peas, mushrooms, garlic, ginger, and cauliflower rice.", 460, "31g", "24 min", []string{"Plant protein", "Low carb", "Low oil"}, []string{"tofu", "broccoli", "snap peas", "mushrooms", "cauliflower rice", "soy"}, []string{"vegetarian", "no restriction", "low carb"}, []string{"soy"}),
		item(models.MealSlotDinner, models.CuisineChinese, "Orange ginger chicken greens", "Chicken breast with orange ginger glaze, broccoli, peppers, snap peas, and brown rice.", 540, "44g", "28 min", []string{"High protein", "Balanced", "Low oil"}, []string{"chicken", "orange", "ginger", "broccoli", "peppers", "brown rice"}, []string{"no restriction"}, nil),
		item(models.MealSlotDinner, models.CuisineMediterranean, "Turkey kofta with couscous salad", "Lean turkey kofta, couscous, tomato, cucumber, mint, lemon, and yogurt sauce.", 560, "43g", "30 min", []string{"Balanced", "Fresh herbs", "Protein rich"}, []string{"turkey", "couscous", "tomato", "cucumber", "yogurt"}, []string{"no restriction"}, []string{"gluten", "dairy"}),
		item(models.MealSlotDinner, models.CuisineMediterranean, "Salmon with roasted vegetables", "Baked salmon with zucchini, peppers, olives, lemon, herbs, and cauliflower mash.", 520, "44g", "28 min", []string{"Omega-3", "Low carb", "Heart healthy"}, []string{"salmon", "zucchini", "peppers", "olives", "cauliflower"}, []string{"pescatarian", "no restriction", "low carb"}, []string{"fish"}),
		item(models.MealSlotDinner, models.CuisineMediterranean, "Stuffed pepper lentil bake", "Bell peppers stuffed with lentils, quinoa, tomato, herbs, feta, and side greens.", 510, "29g", "34 min", []string{"Fiber rich", "Balanced", "Vegetable packed"}, []string{"bell peppers", "lentils", "quinoa", "tomato", "feta"}, []string{"vegetarian", "no restriction"}, []string{"dairy"}),
		item(models.MealSlotDinner, models.CuisineIndian, "Tandoori tofu and vegetable tray", "Spiced tofu, cauliflower, peppers, chickpeas, mint yogurt, and millet.", 540, "32g", "33 min", []string{"Vegetarian", "Anti-inflammatory", "Fiber rich"}, []string{"tofu", "cauliflower", "peppers", "chickpeas", "yogurt", "millet"}, []string{"vegetarian", "no restriction"}, []string{"soy", "dairy"}),
		item(models.MealSlotDinner, models.CuisineIndian, "Palak chickpea bowl", "Spinach curry with chickpeas, tomato, spices, cucumber salad, and cauliflower rice.", 500, "27g", "30 min", []string{"Plant protein", "Low carb", "Iron source"}, []string{"spinach", "chickpeas", "tomato", "cucumber", "cauliflower rice"}, []string{"vegetarian", "no restriction", "low carb"}, nil),
		item(models.MealSlotDinner, models.CuisineIndian, "Chicken saag with cauliflower rice", "Lean chicken cooked with spinach, tomato, ginger, garlic, spices, and cauliflower rice.", 530, "43g", "32 min", []string{"High protein", "Low carb", "Iron source"}, []string{"chicken", "spinach", "tomato", "ginger", "garlic", "cauliflower"}, []string{"no restriction", "low carb"}, nil),
	}
}

func item(slot models.MealSlot, cuisine models.Cuisine, name, description string, calories int, protein, prepTime string, tags, ingredients, diets, allergens []string) models.MealLibraryItem {
	return models.MealLibraryItem{
		Meal: models.Meal{
			Slot:        slot,
			Cuisine:     cuisine,
			Name:        name,
			Description: description,
			Calories:    calories,
			Protein:     protein,
			PrepTime:    prepTime,
			Tags:        tags,
		},
		Ingredients: ingredients,
		Diets:       diets,
		Allergens:   allergens,
		Source:      "seed",
	}
}
